### ISSUE TITLE
2017 Plays slides

### ISSUE THREAD

**Issue by joshhting** [RoboJackets/robocup-training#11]

**Comment by joshhting** [comment]
We want to ditch the binary clock play for line up so that they are not confused by binary concepts.

**Comment by joshhting** [comment]
In order to make things minimally confusing, new recruits should only be required to fill out a couple of key methods to get things working

**Comment by joshhting** [comment]
What if for our 2nd or 3rd play we have them implement something fun like something related to the coach play? Joe mentioned having the robots huddle together and move side to side while in a circle and I think they'd enjoy doing that.

**Comment by joshhting** [comment]
On a more serious note, the first play meeting is in 3 weeks, so if I could get any feedback on at least the  first play slides that would be super

**Comment by JNeiger** [comment]
It might be nice to put in a picture of a general state machine of something in the real world before we start talking about it in the context of soccer. This should help people visualize it a bit easier.

Here's one of an elevator that could work.
![](https://i.stack.imgur.com/vQ3Fi.png)
