### ISSUE TITLE
2017 Contribution slides

### ISSUE THREAD

**Issue by joshhting** [RoboJackets/robocup-training#15]

**Comment by Jason27chan** [comment]
Maybe we can talk more about the reasoning behind this process? Mention that with 90k lines of code, we need to streamline the process of adding code that's clean, readable, and efficient.

Explain the git concepts separately from the git commands. Explain why we use branches, remotes, and commits separate from explaining what the commands are. On the other hand, it might be better to get used to the commands before worrying about the concepts.

**Comment by Jason27chan** [comment]
Something nice would be a straightforward reference sheet, like "in X situation, input these commands"

**Comment by jgkamat** [comment]
I think that the contribution flowchart is a good start to this, but it can definetly be improved. For example, it only covers the high level contribution workflow, and dosen't cover more detailed problems you might encounter.

We might want to steal/make a table with something like:

| Action               | Command                    |
|----------------------+----------------------------|
| change branch        | git checkout <branch name> |
| delete local changes | git reset --hard HEAD      |
| ...                  |                            |

**Comment by joshhting** [comment]
I agree that we should definitely explain the why and how of the contribution process in these slides. We can also break down the process into more granular steps so we can address detailed problems like updating submodules here.
