### ISSUE TITLE
Migrate old files to a 2016 folder

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-training#9]
See discussion in #8.

Blocked on #8.

Once this is done, new slides could be added by copy pasting from the 2016 directory and modifying them (if needed), which would keep the 2016 versions intact.

**Comment by joshhting** [comment]
Should probably revert c778c99 and 9f73c03 for this :P

**Comment by jgkamat** [comment]
Docs have been migrated, let me know if you see any issues or broken links.

**Comment by joshhting** [comment]
FYI the new 2017 training docs do not show up on doxygen

**Comment by jgkamat** [comment]
Yah, right now there's no autodeployment for docs (since that would require an autodeploy to another autodeploy). The new docs page has to be created manually (by copying over the markdown files), but that's not too hard to set up.
